# 15-251 Installing the Google Cloud SDK
sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD) # get the git SHA Travis CI environment variable, accessible by deploy.sh 15-261 Updating the deployment script
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1 # configure GCE CLI to disable interactive prompts
before_install:
- openssl aes-256-cbc -K $encrypted_42099b4af021_key -iv $encrypted_42099b4af021_iv -in pj-renamed-service-account.json.enc -out app/pj-renamed-service-account.json -d # encrypted GCE service account / Travis CI CLI encrypted key file travis-encrypt YAML output line to be pasted here
- curl https://sdk.cloud.google.com | bash > /dev/null;  # fetch config file & copy to instance
- source $HOME/google-cloud-sdk/path.bash.inc # 'source' command is used to apply the config file
- gcloud components update kubectl # install kubectl on instance, for future use (step 8 Apply all configs in k8s folder - see deploy.sh)
- gcloud auth activate-service-account --key-file pj-renamed-service-account.json # equivalent to an (AWS) IAM user account (from secure file)
- gcloud config set project multi-k8s-257409 # NB declare the project config - must use the project's full ID not friendly name
- gcloud config set compute/zone europe-west2-b # declare the zone of the cluster
- gcloud container clusters get-credentials multi-cluster  # declare the cluster to use for k8s commands
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin # non-interactive login (using environment variables)
- docker build -t peternjenkin/react-test -f ./client/Dockerfile.dev ./client # build a new image (dev as only dev d'have code for tests)

script:
# test script to run
  - docker run -e CI=true USERNAME/docker-react npm run test    # tests not really set up; just for practice 16-252 'Running Tests with Travis'

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master