# 14-215 Claim config file (for PVC Persistent Volume Claim)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  volumes:
      -name: postgres-storage
          persistentVolumeClaim:
              claimName: database-persistent-volume-claim
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

