# 14-215 Claim config file (for PVC Persistent Volume Claim)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim # to match in postgres deployment
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

